python attack_pipeline.py \
--n_epoch 5000 \
--lr 0.001 \
--dataset grb-ppi \
--dataset_mode normal \
--data_dir ../data/grb-ppi/ \
--config_dir ./grb-ppi/ \
--feat_norm arctan \
--model_dir ../saved_models/grb-ppi-arctan-ind-sur/ \
--model gcn \
--save_dir ../results/grb-ppi-arctan-ind/ \
--n_attack 10 \
--n_inject 500 \
--n_edge_max 100 \
--feat_lim_min -1 \
--feat_lim_max 1
