python train_pipeline.py \
--n_epoch 8000 \
--dataset grb-cora \
--feat_norm linearize \
--data_dir ../data/grb-cora \
--model_dir ../saved_models/grb-cora-linear-ind/ \
--config_dir ./grb-cora/ \
--dropout 0.5 \
--eval_every 1 \
--save_after 0 \
--early_stop \
--n_train 1 \
--train_mode inductive \
--gpu 0