python attack_pipeline.py \
--n_epoch 2000 \
--lr 0.01 \
--dataset grb-reddit \
--dataset_mode full \
--feat_norm arctan \
--data_dir ../data/grb-reddit/ \
--config_dir ./grb-reddit/ \
--model_dir ../saved_models/grb-reddit-arctan-ind-sur/ \
--model_file 0/checkpoint.pt \
--model gcn \
--save_dir ../results/grb-reddit-arctan-ind/ \
--n_attack 1 \
--n_inject 1500 \
--n_edge_max 200 \
--gpu 1
