python attack_pipeline.py \
--n_epoch 2000 \
--lr 0.01 \
--dataset grb-flickr \
--dataset_mode full \
--data_dir ../data/grb-flickr/ \
--config_dir ./grb-flickr/ \
--feat_norm arctan \
--model_dir ../saved_models/grb-flickr-arctan-ind-sur/ \
--model gcn \
--save_dir ../results/grb-flickr-arctan-ind/ \
--n_attack 1 \
--n_inject 500 \
--n_edge_max 100 \
--feat_lim_min -1 \
--feat_lim_max 1
