python adv_train_pipeline.py \
--n_epoch 12000 \
--dataset grb-flickr \
--feat_norm arctan \
--data_dir ../data/grb-flickr \
--model_dir ../saved_models/grb-flickr-arctan-ind-adv-fgsm-10/ \
--config_dir ./grb-flickr/ \
--dropout 0.5 \
--eval_every 5 \
--save_after 0 \
--early_stop \
--n_train 1 \
--train_mode inductive \
--attack_adv fgsm \
--attack_epoch 10 \
--attack_lr 0.1 \
--n_attack 1 \
--n_inject 200 \
--n_edge_max 100 \
--gpu 0